"use strict";
var platform_browser_dynamic_1 = require('@angular/platform-browser-dynamic');
var common_1 = require('@angular/common');
var platform_browser_1 = require('@angular/platform-browser');
var app_routes_1 = require('./app.routes');
var http_1 = require('@angular/http');
var router_1 = require('@angular/router');
var app_component_1 = require('./app.component');
var event_service_1 = require('./event.service');
var user_service_1 = require('./user.service');
var core_1 = require('@angular/core');
core_1.enableProdMode();
platform_browser_dynamic_1.bootstrap(app_component_1.AppComponent, [platform_browser_1.Title, [router_1.provideRouter(app_routes_1.routes)], http_1.HTTP_PROVIDERS, event_service_1.EventService, user_service_1.UserService, { provide: common_1.LocationStrategy, useClass: common_1.PathLocationStrategy }]);
